image: Visual Studio 2022

build:
  verbosity: normal

environment:

  FACIL_FORCE_REGENERATE: "1"
  FACIL_FAIL_ON_CHANGED_OUTPUT: "1"
  connectionString: Server=(local)\SQL2019;Database=FacilTest;Integrated Security=SSPI

init:
  - net start MSSQL$SQL2019

build_script:
  # Build DB
  - cmd: msbuild src\TestDb\TestDb.sqlproj /property:Configuration=Release
  # Publish DB
  - cmd: sqlpackage.exe /Action:Publish /SourceFile:"src\TestDb\bin\Release\TestDb.dacpac" /TargetConnectionString:"Server=(local)\SQL2019;Database=FacilTest;Integrated Security=SSPI"
  # Build generator
  - cmd: dotnet build -c Release src\Facil.Generator
  # Build the package project, which includes the generator output
  - cmd: dotnet build -c Release src\Facil.Package
  # Pack in a separate step (fails for some reason with "empty lib\" error if using <GeneratePackageOnBuild>)
  - cmd: dotnet pack -c Release src\Facil.Package
  # Build tests, which due to nuget.config should restore the locally built package
  - cmd: dotnet build -c Release src\DbTests

test_script:
  - cmd: dotnet src\DbTests\bin\Release\net5.0\DbTests.dll --fail-on-focused-tests
  - cmd: dotnet src\DbTests\bin\Release\netcoreapp2.1\DbTests.dll --fail-on-focused-tests

artifacts:
  - path: /nupkg/*.nupkg

deploy:
  - provider: NuGet
    api_key:
      secure: OFv8kufIt1T3pwGdeXnw4ihnZxl/xVNuIU3CE3J70qjedx0REMXJ0HS0UpJpO9Gp
    on:
      appveyor_repo_tag: true
