image: Visual Studio 2022

build:
  verbosity: normal

environment:

  FACIL_FORCE_REGENERATE: "1"
  FACIL_FAIL_ON_CHANGED_OUTPUT: "1"
  connectionString: Server=(local)\SQL2019;Database=FacilTest;Integrated Security=SSPI;Encrypt=False

init:
  - net start MSSQL$SQL2019

build_script:

  # Build DB
  - cmd: msbuild src\TestDb\TestDb.sqlproj /property:Configuration=Release

  # Publish DB
  - cmd: sqlpackage.exe /Action:Publish /SourceFile:"src\TestDb\bin\Release\TestDb.dacpac" /TargetConnectionString:"Server=(local)\SQL2019;Database=FacilTest;Integrated Security=SSPI"

  # Build generator
  - cmd: dotnet restore src\Facil.Generator --locked-mode
  - cmd: dotnet build src\Facil.Generator -c Release --no-restore

  # Build the package project, which includes the generator output
  - cmd: dotnet restore src\Facil.Package --locked-mode
  - cmd: dotnet build src\Facil.Package -c Release --no-restore

  # Pack in a separate step (fails for some reason with "empty lib\" error if using <GeneratePackageOnBuild>)
  - cmd: dotnet pack src\Facil.Package -c Release

  # Build tests, which due to nuget.config should restore the locally built package
  - cmd: dotnet build src\DbTests -c Release

test_script:
  - cmd: dotnet src\DbTests\bin\Release\net7.0\DbTests.dll --fail-on-focused-tests

artifacts:
  - path: /nupkg/*.nupkg

deploy:
  - provider: NuGet
    api_key:
      secure: j+6WZ3R8B5x0+GU4DwO6aHPIskERLHUqVRneCn4XBrcXdLfB+XJLQnHgMHMfNEDT
    on:
      appveyor_repo_tag: true
