name: CI

on: [ push, pull_request ]

env:
  FACIL_FORCE_REGENERATE: 1
  FACIL_FAIL_ON_CHANGED_OUTPUT: 1

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Restore tools
        run: dotnet tool restore

      - name: Check code format
        run: dotnet fantomas --check --recurse .

      - name: Install SQL Server - docker pull
        run: docker pull samuelmarks/mssql-server-fts-sqlpackage-linux

      - name: Install SQL Server - docker run
        run: docker run -d -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=pwd' -p 1433:1433 --name sqlfts0 samuelmarks/mssql-server-fts-sqlpackage-linux

      - name: Create default DB
        run: docker exec sqlfts0 /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'pwd' -Q 'CREATE DATABASE FacilTest'

      - name: Build DB
        run: dotnet build src/TestDb/TestDb.sqlproj -c Release

      - name: Publish DB
        run: dotnet sqlpackage /Action:Publish /SourceFile:"src/TestDb/bin/Release/TestDb.dacpac" /TargetConnectionString:"Data Source=localhost;Database=FacilTest;User ID=sa;Password=dbatools.I0;TrustServerCertificate=True"

      - name: Restore generator
        run: dotnet restore src/Facil.Generator --locked-mode

      - name: Build generator
        run: dotnet build src/Facil.Generator -c Release --no-restore

      - name: Restore package project
        run: dotnet restore src/Facil.Package --locked-mode

      - name: Build package project
        run: dotnet build src/Facil.Package -c Release --no-restore

      # Pack in a separate step (fails for some reason with "empty lib/" error if using <GeneratePackageOnBuild>)
      - name: Pack
        run: dotnet pack src/Facil.Package -c Release

      # Build tests, which due to nuget.config should restore the locally built package
      - name: Build tests
        run: dotnet build src/DbTests -c Release

      - name: Test
        run: dotnet src/DbTests/bin/Release/net7.0/DbTests.dll --fail-on-focused-tests

      - name: Push
        if: startsWith(github.ref, 'refs/tags/v/')
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "**/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k "$NUGET_API_KEY" --skip-duplicate
